### ISSUE TITLE
Unable to Create or Update

### ISSUE THREAD

**Issue by VimalN-SRG** [flyisland/solconfig#5]
Hi, thank you for create this app. It is very useful.

I have been able to successfully run the backup process and created a file called `config.backup.json`.

However, when I try to use create or update the functions, I get the NullPointerException exception error.

Any help will be appreciated.

`# java -jar solconfig.jar -H=xxxxx -u=xxxxx -p=xxxxx create config.backup.json`

`java.lang.NullPointerException
        at com.solace.tools.solconfig.SempClient.freeMakerToString(SempClient.java:223)
        at com.solace.tools.solconfig.SempClient.readMapFromJsonFile(SempClient.java:211)
        at com.solace.tools.solconfig.Commander.getConfigBrokerFromFile(Commander.java:109)
        at com.solace.tools.solconfig.Commander.create(Commander.java:95)
        at com.solace.tools.solconfig.cli.CreateCommand.execute(CreateCommand.java:24)
        at com.solace.tools.solconfig.cli.SubCommand.call(SubCommand.java:15)
        at com.solace.tools.solconfig.cli.SubCommand.call(SubCommand.java:7)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.solace.tools.solconfig.App.main(App.java:11)`

**Comment by flyisland** [comment]
Hi @VimalN-SRG, Glad to know this tool is useful to you.

This is a known bug I just fixed a couple of days ago, the workaround is to use the filename with a folder prefix like `java -jar solconfig.jar -H=xxxxx -u=xxxxx -p=xxxxx ./create config.backup.json`, or you could download the latest release [v1.1.5](https://github.com/flyisland/solconfig/releases/tag/1.1.5).
